### ISSUE TITLE
chore: textarea border, button 색상, 로그에서 todo, column 구분

### ISSUE THREAD

**Issue by LimHaksu** [woowa-techcamp-2020/todo-10#130]
## 이슈 요약
extarea border, button 색상, 로그에서 todo, column 구분

## 체크리스트
- [x] textarea border-radius 10px 10px 0 10px
- [x] button green 색상 header와 똑같게
- [x] 'column', 'todo' 회색으로 이름앞에 표시하기
- [x] todo 추가할 때 빈칸만 입력할 경우 버튼 비활성화
